/** Maps effect name (as shown in effectNames.ts) to its real-world pedal/amp description.
 *  Source: Valeton GP-200 FX List V2 (community-compiled) */
export const EFFECT_DESCRIPTIONS: Record<string, string> = {
  // ── PRE ──────────────────────────────────────────────────────────────
  'COMP': 'Ross™ Compressor',
  'COMP4': 'Keeley® C4 4-knob compressor',
  'S-Comp': 'Flexible, fully adjustable compressor effect',
  'Micro Boost': 'MXR® M133 Micro Amp',
  'AC Boost': 'Xotic® AC Booster',
  'B-Boost': 'Xotic® BB Preamp',
  'P-Boost': 'Xotic® RC Booster',
  '14 Boost': 'Fortin® Grind',
  'FAT BB': 'Fulltone® Fat Boost',
  'Boost': 'Xotic® EP Booster',
  'AC Refiner': 'For acoustic instruments, bringing a more natural sound',
  'AC Sim': 'Boss® AC-2 Acoustic Simulator',
  'T-Wah': 'Touch wah — control the wah sound by playing intensity',
  'A-WAH': 'Variable auto wah effect',
  'Step Filter': 'A 4-step auto filter machine for creating synth-like sounds',
  'OCTA': 'Polyphonic octave effect',
  'Pitch': 'Polyphonic pitch shifter/harmonizer (CTRL: Dry only)',
  'P-Bend': 'Polyphonic pitch shifter/harmonizer (CTRL: Wet/Dry)',
  'Ring Mod': 'Ring modulator for creating inharmonic frequencies (like bells and chimes)',
  'Saturate': 'Vintage tape saturation simulator',

  // ── WAH ──────────────────────────────────────────────────────────────
  'V-Wah': 'VOX® V846',
  'C-Wah': "Dunlop® CryBaby® (Classic 60's)",
  'P-Wah': "John Petrucci's rack wah settings, Volume, Q, and six EQ controls",
  'S-Wah': 'Classic wah tone',
  'B-Wah': 'Wah designed for basses',

  // ── DST ──────────────────────────────────────────────────────────────
  'Green OD': 'Ibanez® TS-808 Tube Screamer',
  'OD 9': 'Ibanez® TS9 Tube Screamer',
  'Yellow OD': 'DOD 250 Preamp Overdrive',
  'Penesas': 'Klon® Centaur (Gold Overdrive)',
  'Swarm': 'Providence® SOV-2 Stampede',
  'Super OD': 'Boss SD-1 Super Overdrive',
  'Scream OD': 'Tube Screamer® style overdrive pedal',
  'Blues OD': 'Boss BD-2 Blues Driver',
  'Force': 'Fulltone® OCD',
  'Blues Master': 'Marshall® BluesBreaker',
  'Master OD': 'Marshall JVM410 / JCM800 tone EQ stage',
  'TaiChi OD': 'Hermida® Zendrive®',
  'Timmy OD': 'Paul Cochrane® Timmy overdrive',
  'Precise OD': 'Horizon Devices® Precision Drive',
  'Lazaro': 'Electro-Harmonix® Big Muff Pi® fuzz/distortion pedal',
  'Red Haze': 'Dallas-Arbiter® Fuzz Face',
  'Sora Fuzz': 'Sola Sound® Tone Bender',
  'Plustortion': 'MXR® M104 Distortion +',
  'SM Dist': 'Boss DS-1 Distortion',
  'Darktale': 'ProCo™ The Rat (early LM308 op-amp version)',
  'Chief': "Marshall® Guv'nor",
  'Master Dist': 'Marshall® Shredmaster Distortion',
  'La Charger': 'MI Audio® Crunch Box',
  'Black Bass': 'Darkglass Microtubes B7K',

  // ── AMP ──────────────────────────────────────────────────────────────
  'Tweedy': 'Fender® Tweed Deluxe',
  'Bellman 59N': "Fender® '59 Bassman",
  'Bellman 59B': "Based on Fender® '59 Bassman",
  'Dark Twin': "Fender® '65 Twin Reverb",
  'Dark DLX': 'Fender® Deluxe Reverb',
  'Dark Vibra': 'Fender® Vibroverb',
  'Silver Twin': 'Fender® Silverface Twin Reverb',
  'SUPDual CL': 'Supro® Dual-Tone 1624T (CH1 clean tone)',
  'SUPDual OD': 'Supro® Dual-Tone 1624T (CH2 dirty tone)',
  'Foxy 15TB': 'VOX® AC-100 bass amp',
  'Foxy 30N': 'VOX® AC30HW (Clean)',
  'Foxy 30TB': 'VOX® AC30HW (Drive)',
  'J-120 CL': 'Roland JC-120 Jazz Chorus solid state combo',
  'Match CL': 'Matchless™ Chieftain 212 combo (Clean)',
  'Match OD': 'Matchless™ Chieftain 212 combo (Overdrive)',
  'L-Star CL': 'Mesa/Boogie® Lone Star™ (Clean)',
  'L-Star OD': 'Mesa/Boogie® Lone Star™ (Overdrive)',
  'BogSV CL': 'Bogner® Shiva 20th Anniversary version (Clean)',
  'BogSV OD': 'Bogner® Shiva 20th Anniversary version (Overdrive)',
  'Bog BlueV': 'Bogner® XTC blue channel',
  'Bog BlueM': 'Bogner® XTC blue channel',
  'Bog RedV': 'Bogner® XTC red channel',
  'Bog RedM': 'Bogner® XTC red channel',
  'Z38 CL': 'Dr. Z® Maz 38 Sr. combo (Clean)',
  'Z38 OD': 'Dr. Z® Maz 38 Sr. combo (Overdrive)',
  'Knights CL': 'Grindrod® Pendragon PG20C (Clean, Bright OFF)',
  'Knights CL+': 'Grindrod® Pendragon PG20C (Clean, Bright ON)',
  'Knights OD': 'Grindrod® Pendragon PG20C (Overdrive)',
  'Bad-KT CL': 'Bad Cat® Hot Cat 30 (Clean)',
  'Bad-KT OD': 'Bad Cat® Hot Cat 30 (Overdrive)',
  'Solo100 CL': 'Soldano® SLO100 (Clean)',
  'Solo100 OD': 'Soldano® SLO100 (Crunch)',
  'Solo100 LD': 'Soldano® SLO100 (Overdrive)',
  'UK 45': 'Marshall® JTM45 (normal channel)',
  'UK 45+': 'Marshall® JTM45',
  'UK 45JP': 'Marshall® JTM45 (Jumper normal to Channel 2)',
  'UK 50': 'Marshall® JMP50 (normal channel)',
  'UK 50+': 'Marshall® JMP50',
  'UK 50JP': 'Marshall® JMP50 (Jumper normal to Channel 2)',
  'UK SLP': 'Marshall 1959HW™',
  'UK 800': 'Marshall® JCM800',
  'UK 900': 'Marshall® JCM900',
  'Flagman 1': 'Friedman BE100 Plexi Channel',
  'Flagman 2': 'Friedman BE 100 Deluxe Plexi Channel',
  'Flagman+ 1': 'Friedman BE100 Plexi Channel',
  'Flagman+ 2': 'Friedman BE 100 Deluxe Brown Eye Channel',
  'Mess2C+ 1': 'Mesa/Boogie® Mark II C+',
  'Mess2C+ 2': 'Mesa/Boogie® Mark II C+',
  'Mess2C+ 3': 'Mesa/Boogie® Mark II C+',
  'Mess4 LD': 'Mesa/Boogie® Mark IV™ (Lead channel)',
  'Mess4 LD 2': 'Mesa/Boogie® Mark IV™ (Lead 2 channel)',
  'Mess4 LD 3': 'Mesa/Boogie® Mark IV™ (Lead 3 channel)',
  'Mess DualV': 'Mesa/Boogie® Dual Rectifier® (Vintage mode)',
  'Mess DualM': 'Mesa/Boogie® Dual Rectifier® (Modern mode)',
  'Juice30 OD': 'Orange® AD30™ (Dirty channel)',
  'Juice R100': 'Orange® Rockerverb 100™ (Dirty channel)',
  'EV 51': 'Peavey® 5150® (LEAD channel)',
  'Eagle 120': 'ENGL® Savage 120 Amplifier',
  'Eagle 120+': 'ENGL® Savage 120 Amplifier',
  'Power LD': 'ENGL® Powerball II E645/2 (CH4)',
  'Dizz VH': 'Diezel® VH4 — Channel 1 (Clean)',
  'Dizz VH S': 'Diezel® VH4 — Channel 2 (Crunch)',
  'Dizz VH+': 'Diezel® VH4 — Channel 3 (Distortion)',
  'Dizz VH+ S': 'Diezel® VH4 — Channel 4 (Ultra High Gain)',
  'Classic Bass': 'Ampeg® SVT bass amp',
  'Foxy Bass': 'VOX® AC-100 bass amp',
  'Mess Bass': 'Mesa/Boogie® Bass 400',
  'Mini Bass': 'Ampeg® B-15 "Flip Top" bass',
  'Bass Pre': 'Alembic™ F-2B preamp',
  'AC Pre': 'AER® Colourizer 2 acoustic preamp — EQ F1: 90Hz to 1.6kHz',
  'AC Pre 2': 'AER® Colourizer 2 acoustic preamp — EQ F2: 680Hz to 11kHz',

  // ── NR ───────────────────────────────────────────────────────────────
  'Gate 1': 'ISP® Decimator™ noise gate',
  'Gate 2': 'Flexible noise gate with attack and release control',

  // ── CAB ──────────────────────────────────────────────────────────────
  'SUP ZEP': 'Supro® 1x6" cabinet with oval speaker',
  'TWD CP': 'Vintage Fender® Champ 1x8" cabinet',
  'TWD PRC': 'Vintage Fender® Princeton 1x10" cabinet',
  'TWD SUP': 'Fender® Tweed 2x10" cabinet',
  'TWD LUX': 'Fender® Tweed Deluxe 1x12 cabinet',
  'DARK LUX': 'Vintage Fender® Deluxe 1x12" cabinet',
  'DARK VIT': 'Vintage Fender® Vibrolux 1x12" cabinet',
  'Dark CS': 'Custom modified Fender® 2x12" cabinet',
  'Bellman 1': 'Vintage Fender® "Piggyback" Bassman® 2x12" cabinet',
  'Bellman 2': "Fender® '59 Bassman® 4x10\" cabinet",
  'J-120': 'Roland Jazz Chorus 2x12" cabinet',
  'UK G12': 'Marshall® 1x12" cabinet',
  'UK GRN 1': 'Marshall® 2550 2x12" cabinet',
  'UK LD': 'Marshall® 1960AV 4x12" cabinet',
  'UK TD': '68 Marshall® Basketweave 4x12" cabinet',
  'UK MD': 'Custom modified Marshall® 4x12" cabinet',
  'UK GRN 2': 'Vintage Marshall® 4x12" cabinet with Celestion® Greenback® speakers',
  'UK 75': 'Marshall® 4x12" cabinet with Celestion® G12T-75 speakers',
  'UK Dark': '1968 Marshall® 4x12" cabinet',
  'FOXY 1': 'Vintage VOX® AC15 1x12" cabinet',
  'FOXY 2': 'Vintage VOX® AC30 2x12" cabinet',
  'ROUT': 'Carr® Rambler 1x12" cabinet',
  'BogSV': 'Bogner® Shiva 1x12" cabinet',
  'Bad-KT': 'Bad Cat® Hot Cat 1x12" cabinet',
  'Match': 'Matchless® Chieftain 2x12" cabinet',
  'TOM OPEN': 'Swart® Atomic Space 1x12" cabinet',
  'ACE': 'Morgan® AC-20 Deluxe 1x12 cabinet',
  'Mess': 'Mesa/Boogie® Rectifier® 4x12" cabinet',
  'D STAR': 'Mesa/Boogie® Lonestar 1x12" cabinet',
  'SUP Star': 'Mesa/Boogie® Lonestar 2x12" cabinet',
  'US STO': "1980's Mesa/Boogie® 1x12\" cabinet",
  'BOUTI': 'A unique custom 2x12" cabinet',
  'SUP': 'Supro® 1624T 2x12 cabinet',
  'MATT TWD': 'Matchless® 2x12" cabinet',
  'Freed': 'Fryette® Deliverance 2x12" cabinet',
  'DB Rock': 'Two-Rock® 2x12" cabinet',
  'Blue SK': 'Custom 2x12" cabinet with Celestion® Alnico Blue speakers',
  'EV': 'Peavey® 6505 4x12" cabinet',
  'Bog': 'Bogner® 4x12" cabinet',
  'Eagle': 'ENGL® 4x12" cabinet',
  'Uban': 'Bogner® Uberkab 4x12" cabinet',
  'Solo': 'Soldano® 4x12" cabinet',
  'Juice': 'Orange® PPC412 4x12" cabinet',
  'H-WAY': 'Vintage Hiwatt® SE4123 4x12" cabinet',
  'Way': 'Vintage WEM® 4x12" cabinet',
  'Dumb': 'Dumble® 4x12" cabinet',
  'Dizz': 'Diezel® 4x12" cabinet',
  'TRP': 'Hughes & Kettner® Triamp 4x12" cabinet',
  'King': 'Mesa/Boogie® Road King® 4x12" cabinet',
  'ADM 1': 'David Eden® 1x15" bass cabinet',
  'ADM 2': 'David Eden® 4x10" bass cabinet',
  'Workman 1': 'SWR® 1x15" bass cabinet',
  'Workman 2': "SWR® Workingman's 4x10\" bass cabinet",
  'US BASS': 'Mesa/Boogie® 2x10" bass cabinet',
  'MATT': 'Mark Bass® 2x10" bass cabinet',
  'F-TOP': 'Ampeg® PF-115HE 1x15" bass cabinet',
  'AMPG 1': 'Ampeg® SVT-410HE 4x10" bass cabinet',
  'AMPG 2': 'Ampeg SVT-810E 8x10" bass cabinet',
  'HACK': 'Hartke® 4x12" bass cabinet',
  'AC': 'Dreadnought guitar simulation',
  'AC Dream': 'Dreadnought guitar simulation 2',
  'OM': 'Simulates an OM type acoustic guitar',
  'JUMBO': 'Simulates a jumbo acoustic guitar',
  'Bird': 'Simulates the iconic "H-Bird" acoustic guitar',
  'GA': 'Simulates a GA type acoustic guitar',
  'Classic AC': 'Simulates a classical guitar',
  'Mandolin': 'Simulates a mandolin',
  'Fretless Bass': 'Simulates a fretless acoustic bass',
  'Double Bass': 'Simulates a double bass',
  'User IR': 'User IR WAV (44kHz/1024 sample rate)',

  // ── EQ ───────────────────────────────────────────────────────────────
  'Guitar EQ 1': '5 Band EQ for guitars (125Hz, 400Hz, 800Hz, 1.6kHz, 4kHz)',
  'Guitar EQ 2': '5 Band EQ for guitars (100Hz, 500Hz, 1kHz, 3kHz, 6kHz)',
  'Bass EQ 1': 'Equalizer for bass',
  'Bass EQ 2': 'Equalizer for bass',
  'Mess EQ': 'Mesa/Boogie® amps 5 band EQ',
  'Hyper EQ': '10-band graphic EQ suitable for any instrument',

  // ── MOD ──────────────────────────────────────────────────────────────
  'G-Chorus': 'Boss CE-2 Chorus Ensemble',
  'C-Chorus': 'Boss DC-2 Dimension C',
  'B-Chorus': 'Chorus for bassists',
  'M-Chorus': 'A multi-dimensional chorus pedal',
  'Jet': 'Classic flanger effect',
  'B-Jet': 'Classic flanger effect for bass',
  'N-Jet': 'A flanger with negative feedback, producing "underwater" style sound',
  'Trem Jet': 'Combines flanger and tremolo in one',
  'V-Roto': 'Analog BBD chorus pedal (vibrato mode)',
  'G-Roto': 'Legendary huge ensemble chorus pedal from the late 1970s (vibrato mode)',
  'Vibrato': 'A classic vibrato',
  'O-Phase': 'MXR® M101 Phase 90',
  'G-Phase': 'Boss PH-1® Phaser — BBD-based green phase pedal',
  'S-Phase': 'Electro-Harmonix® Small Stone',
  'Pan Phase': 'A special, subtle phaser combining tremolo/pan variations',
  'M-Vibe': 'Voodoo Lab® Micro Vibe',
  'Vibe': 'Shin-Ei Uni-Vibe classic phase shifter (chorus)',
  'O-Trem': 'Demeter® TRM-1 Tremulator',
  'Sine Trem': 'Sine tremolo waveform with super wide tonal range',
  'Triangle Trem': 'Triangle tremolo waveform with super wide tonal range',
  'Bias Trem': 'Bias tremolo waveform with super wide tonal range',
  'Detune': 'Detuning effect that combines slightly shifted signal to create a chorus-like sound',
  'Bit Smash': 'Bitcrushing/sample reducing effect',
  'Auto Swell': 'Auto swell effect — makes guitar sound like violin',

  // ── DLY ──────────────────────────────────────────────────────────────
  'BBD Delay S': 'Delay based on BBD analog delay',
  'Digital Delay S': 'Digital delay',
  'Tape Delay S': 'Delay/echo effect using tape machine simulation',
  'Ambience 1': 'Multi-tap delay (tonal variation 1)',
  'Ambience 2': 'Multi-tap delay (tonal variation 2)',
  'Pure': 'Pure, precise delay sound',
  'Analog': 'Warm delay sound with analog feel',
  'Tape': 'Roland RE-201 Space Echo',
  'Ping Pong': 'Ping-pong delay producing stereo feedback bounces Left-Right',
  'Slapback': 'Classic slapback echo',
  'Sweep Echo': 'Delay effect with sweeping filter modulated repeats',
  'Ring Echo': 'Delay effect with ring modulated repeats',
  'M-Echo': 'A multi-tap delay simulating a huge 4-head tape echo machine',
  'Sweet Echo': 'Classic analog delay pedal (1981–1984 era)',
  '999 Echo': 'Maxon® AD900 Analog Delay',
  'Vintage Rack': "Vintage 1980's rack-mount delay machine",
  'Lofi Echo': 'Lo-fi delay effect',
  'Tube': 'Simulates tube-driven tape echo sound',
  'Rev Echo': 'Special delay effect with reversed feedback',

  // ── RVB ──────────────────────────────────────────────────────────────
  'Room': 'Room reverb simulation',
  'Hall': 'Hall reverb simulation',
  'Church': 'Church reverb simulation',
  'Plate': 'EMT 140 plate reverb',
  'Spring': 'Roland RE-201 Space Echo spring reverb',
  'Studio': 'Recording studio reverb simulation',
  'Club': 'Club reverb simulation',
  'Concert': 'Concert hall reverb simulation',
  'Arena': 'Arena reverb simulation',
  'N-Star': 'Special-tuned reverb with lush bright decays',
  'Deepsea': 'Special-tuned reverb with huge deep decays',
  'Sweet Space': 'Modulated reverb that is lush and sweet',
  'Shimmer': 'Rich, shimmering reverb',

  // ── VOL ──────────────────────────────────────────────────────────────
  'Volume': 'Pure volume control',
};
